### ISSUE TITLE
Add a cluster-aware dynamic client

### ISSUE THREAD

**Issue by fabianvf** [kcp-dev/apimachinery#29]
We need a cluster-aware implementation of client-go's dynamic client.

The current implementation in kcp-dev/kubernetes is a good place to start: https://github.com/kcp-dev/kubernetes/blob/feature-logical-clusters-1.23/staging/src/k8s.io/client-go/dynamic/simple.go

We can likely do something similar to [what we did for the discovery client](https://github.com/kcp-dev/apimachinery/pull/22), where we can scope the client config and delegate to a regular dynamic client on a per-cluster basis, and then implement only the supported cross-cluster methods for cross-cluster dynamic client requests (just list/watch?).

**Comment by ncdc** [comment]
I think we'd want a full dynamic client, for all verbs?

**Comment by fabianvf** [comment]
Can you do a cross-cluster delete/update/patch?

**Comment by ncdc** [comment]
No but the dynamic client is more than just for wildcard list/watch. You can do dynamicClusterClient.Cluster("root:org:ws").CoreV1().Secrets....

**Comment by fabianvf** [comment]
Yeah, but if we've scoped down the config already the regular dynamic client can handle everything after the `.Cluster(x)`, right?

**Comment by ncdc** [comment]
Fixed by #30
